import { Courses } from "@/screens/courses/page";
import { CoursesService } from "@/service/coursesService/service";
import { Metadata } from "next";
import "semantic-ui-css/semantic.min.css";

export const metadata: Metadata = {
    title: "Курсы",
    description: "Generated by create next app",
};

export default async function Home() {
    const courses_ = await CoursesService.getCourses();
    return <Courses coursesInfo={courses_} />;
}
